[package]
name = "project"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"
rand = "0.8.3"

[[bench]]
name = "benches"
harness = false
